[[main]]
identifier = 'about'
pageRef = '/about'
weight = 10
[[main]]
identifier = 'team'
pageRef = '/team'
weight = 20
[[main]]
identifier = 'events_news'
pageRef = '/events-news'
weight = 30
[[main]]
identifier = 'projects'
pageRef = '/projects'
weight = 40
[[main]]
identifier = 'join_us'
pageRef = '/join-us'
weight = 50
[[main]]
identifier = 'contact'
pageRef = '/contact'
weight = 60

[[footer]]
identifier = 'footer_about'
weight = 10
[[footer]]
identifier = 'about'
pageRef = '/about'
parent = 'footer_about'
weight = 11
[[footer]]
identifier = 'team'
pageRef = '/team'
parent = 'footer_about'
weight = 12
[[footer]]
identifier = 'footer_involve'
weight = 20
[[footer]]
identifier = 'join_us'
pageRef = '/join-us'
parent= 'footer_involve'
weight = 21
[[footer]]
identifier = 'footer_events'
pageRef = '/events-news'
parent= 'footer_involve'
weight = 22
[[footer]]
identifier = 'contact'
pageRef = '/contact'
parent= 'footer_involve'
weight = 23
[[footer]]
identifier = 'donate'
url = 'https://www.darujme.cz/projekt/1210263?locale=en'
parent= 'footer_involve'
weight = 24
